// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://gxrnofnugxctgebsliuh.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imd4cm5vZm51Z3hjdGdlYnNsaXVoIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTEyMjM4MjQsImV4cCI6MjA2Njc5OTgyNH0.uzLiGCCCcwvIoNYCxsSM-HWG1eKl637KJIEVKcRDnzA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});